use_frameworks!

platform :ios, '8.0'

target 'hcCatagery_Example' do
  pod 'hcCatagery', :path => '../'

  target 'hcCatagery_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
